spring:
    profiles: default
    
service:
  name: WebService
  version: v0.0.2
  
session: 
    address: "192.168.0.107"
    port: 11211

google:
  authUrl: "https://accounts.google.com/o/oauth2/v2/auth"
  clientId: "353579146814-vc3ht3jgbo4ntk3tdstc6f3q48e0v428.apps.googleusercontent.com"
  redirectUrlConsent: "http://localhost:8080/api/fetchAccessTokens"
  redirectUrlToken: "http://localhost:8080/api/home"
  responseType: "code"
  scope:
    userEmail: "https://www.googleapis.com/auth/userinfo.email"
    userProfile: "https://www.googleapis.com/auth/userinfo.profile"
  accessType: "offline"
  includeGrantedScopes: "true"
  prompt:
    selectAccount: "select_account"
    consent: "consent"
  tokenUrl: "https://oauth2.googleapis.com/token"
  grantType: "authorization_code"
  clientSecretPath: "C:\\git\\Chazuke\\Secrets\\WebService\\client_secret_353579146814-vc3ht3jgbo4ntk3tdstc6f3q48e0v428.apps.googleusercontent.com.json"
    
logging:
  level:
    org:
      springframework:
        web: "ERROR"
    com:
      web:
        service: "DEBUG"
  pattern:    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"