spring:
    profiles: default
    
service:
  name: WebService
  version: v0.0.2
  
session: 
    address: "192.168.0.107"
    port: 11211
    
logging:
  level:
    org:
      springframework:
        web: "ERROR"
    com:
      web:
        service: "DEBUG"
  pattern:    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"